default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: storage/development
